<?php

return [
    'provincias' => [
        'A Coruña' => 'Galicia',
        'Álava' => 'País Vasco',
        'Albacete' => 'Castilla-La Mancha',
        'Alicante' => 'Comunidad Valenciana',
        'Almería' => 'Andalucía',
        'Asturias' => 'Principado de Asturias',
        'Ávila' => 'Castilla y León',
        'Badajoz' => 'Extremadura',
        'Barcelona' => 'Cataluña',
        'Burgos' => 'Castilla y León',
        'Cáceres' => 'Extremadura',
        'Cádiz' => 'Andalucía',
        'Cantabria' => 'Cantabria',
        'Castellón' => 'Comunidad Valenciana',
        'Ciudad Real' => 'Castilla-La Mancha',
        'Córdoba' => 'Andalucía',
        'Cuenca' => 'Castilla-La Mancha',
        'Girona' => 'Cataluña',
        'Granada' => 'Andalucía',
        'Guadalajara' => 'Castilla-La Mancha',
        'Guipúzcoa' => 'País Vasco',
        'Huelva' => 'Andalucía',
        'Huesca' => 'Aragón',
        'Islas Baleares' => 'Islas Baleares',
        'Jaén' => 'Andalucía',
        'La Rioja' => 'La Rioja',
        'Las Palmas' => 'Canarias',
        'León' => 'Castilla y León',
        'Lérida' => 'Cataluña',
        'Lugo' => 'Galicia',
        'Madrid' => 'Comunidad de Madrid',
        'Málaga' => 'Andalucía',
        'Murcia' => 'Región de Murcia',
        'Navarra' => 'Comunidad Foral de Navarra',
        'Ourense' => 'Galicia',
        'Palencia' => 'Castilla y León',
        'Pontevedra' => 'Galicia',
        'Salamanca' => 'Castilla y León',
        'Santa Cruz de Tenerife' => 'Canarias',
        'Segovia' => 'Castilla y León',
        'Sevilla' => 'Andalucía',
        'Soria' => 'Castilla y León',
        'Tarragona' => 'Cataluña',
        'Teruel' => 'Aragón',
        'Toledo' => 'Castilla-La Mancha',
        'Valencia' => 'Comunidad Valenciana',
        'Valladolid' => 'Castilla y León',
        'Vizcaya' => 'País Vasco',
        'Zamora' => 'Castilla y León',
        'Zaragoza' => 'Aragón',
    ],
];
